apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::080266302756:role/eksctl-my-cluster-nodegroup-ng-2-NodeInstanceRole-1PQMREK4T8SPS
      username: system:node:{{EC2PrivateDNSName}}

    - groups:
      - system:masters
      rolearn: arn:aws:iam::080266302756:role/aws-eks-codebuild-role
      username: build

  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-06-03T08:50:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1701"
  uid: dd4aff67-2bf4-4e9d-9dae-da19b9aa5f01
